### ISSUE TITLE
how to use your translation api

### ISSUE THREAD

**Issue by nasserkhosravi** [anandmuralidhar24/SimpleVRAndroid#1]
I'm trying  to make an application that uses sensor translation ,I'm wondering  how do you manage that in your app?

thanks.

**Comment by anandmuralidhar24** [comment]
Sensor translation can be more complicated to model since we need to aggregate readings from sensors. We may also need to calibrate sensors to accurately determine the position. If you want to incorporate it, then you need to design an algorithm for computing translation. Then adding the algo in the app should be quite similar to whatever we have done.
